//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMileny.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightSchedules
    {
        public FlightSchedules()
        {
            this.Trips = new HashSet<Trips>();
        }
    
        public int FlightScheduleId { get; set; }
        public System.DateTime Departure { get; set; }
        public Nullable<System.DateTime> ActualDeparture { get; set; }
        public System.TimeSpan Duration { get; set; }
        public int FlightId { get; set; }
    
        public virtual Flights Flights { get; set; }
        public virtual ICollection<Trips> Trips { get; set; }
    }
}
