//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMileny.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlueYonderEntities : DbContext
    {
        public BlueYonderEntities()
            : base("name=BlueYonderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Flights> Flights { get; set; }
        public DbSet<FlightSchedules> FlightSchedules { get; set; }
        public DbSet<Locations> Locations { get; set; }
        public DbSet<Reservations> Reservations { get; set; }
        public DbSet<Travelers> Travelers { get; set; }
        public DbSet<Trips> Trips { get; set; }
    }
}
