//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testMileny.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trips
    {
        public Trips()
        {
            this.Reservations = new HashSet<Reservations>();
            this.Reservations1 = new HashSet<Reservations>();
        }
    
        public int TripId { get; set; }
        public int FlightScheduleID { get; set; }
        public int Status { get; set; }
        public int Class { get; set; }
        public string ThumbnailImage { get; set; }
    
        public virtual FlightSchedules FlightSchedules { get; set; }
        public virtual ICollection<Reservations> Reservations { get; set; }
        public virtual ICollection<Reservations> Reservations1 { get; set; }
    }
}
